name: Docker Build and Release
on: [ push ]
env:
  GITHUB_ACCESSTOKEN: ${{ secrets.ACCESSTOKEN }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Compile, build and push
        run: |
          mvn package 
          docker build -t ghcr.io/mefabc24/pet-clinic:latest .
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.ACCESSTOKEN }}
          docker push ghcr.io/mefabc24/pet-clinic:latest